-- EdTech Customer Churn Reduction Strategy
-- Business analysis SQL library
-- Source tables are generated by the synthetic data pipeline.

-- 01. Customer-level churn summary
SELECT
    customer_id,
    customer_segment,
    churn_flag,
    total_revenue,
    course_completion_rate,
    avg_session_duration_minutes,
    sessions_last_30_days,
    support_ticket_count
FROM customer_360;

-- 02. Churn rate by segment
SELECT
    customer_segment,
    COUNT(*) AS customers,
    SUM(churn_flag) AS churned_customers,
    ROUND(100.0 * SUM(churn_flag) / COUNT(*), 2) AS churn_rate_pct
FROM customer_360
GROUP BY customer_segment
ORDER BY churn_rate_pct DESC;

-- 03. Churn by subscription plan
SELECT
    subscription_plan,
    COUNT(*) AS customers,
    SUM(churn_flag) AS churned_customers,
    ROUND(100.0 * SUM(churn_flag) / COUNT(*), 2) AS churn_rate_pct
FROM customer_360
GROUP BY subscription_plan
ORDER BY churn_rate_pct DESC;

-- 04. Engagement and churn
SELECT
    CASE
        WHEN sessions_last_30_days = 0 THEN 'Inactive'
        WHEN sessions_last_30_days <= 3 THEN 'Low'
        WHEN sessions_last_30_days <= 10 THEN 'Medium'
        ELSE 'High'
    END AS engagement_band,
    COUNT(*) AS customers,
    ROUND(100.0 * SUM(churn_flag) / COUNT(*), 2) AS churn_rate_pct
FROM customer_360
GROUP BY engagement_band
ORDER BY churn_rate_pct DESC;

-- 05. Course completion and churn
SELECT
    CASE
        WHEN course_completion_rate < 25 THEN '0-24%'
        WHEN course_completion_rate < 50 THEN '25-49%'
        WHEN course_completion_rate < 75 THEN '50-74%'
        ELSE '75-100%'
    END AS completion_band,
    COUNT(*) AS customers,
    ROUND(100.0 * SUM(churn_flag) / COUNT(*), 2) AS churn_rate_pct
FROM customer_360
GROUP BY completion_band
ORDER BY churn_rate_pct DESC;

-- 06. Renewal performance
SELECT
    subscription_plan,
    COUNT(*) AS subscriptions,
    SUM(renewal_flag) AS renewals,
    ROUND(100.0 * SUM(renewal_flag) / COUNT(*), 2) AS renewal_rate_pct
FROM subscriptions
GROUP BY subscription_plan
ORDER BY renewal_rate_pct DESC;
